/*
 * k_os (Konnex Operating-System based on the OSEK/VDX-Standard).
 *
 * (C) 2007-2010 by Christoph Schueler <chris@konnex-tools.de,
 *                                      cpu12.gems@googlemail.com>
 *
 * All Rights Reserved
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */
#if !defined(__COMPILER_CFG_H)
#define	__COMPILER_CFG_H

/*
**  Empty 'defines' for now, need Configuration Tool.
*/

#define OS_CODE
#define OS_VAR_NOINIT
#define OS_VAR_POWER_ON_INIT
#define OS_VAR_FAST
#define OS_VAR
#define OS_CONST_BOOLEAN
#define OS_CONST_8BIT
#define OS_CONST_16BIT
#define OS_CONST_32BIT
#define OS_CONST_UNSPECIFIED
#define OS_APPL_DATA
#define OS_APPL_CONST
#define OS_APPL_CODE

#define ECUM_CODE
#define ECUM_VAR_NOINIT
#define ECUM_VAR_POWER_ON_INIT
#define ECUM_VAR_FAST
#define ECUM_VAR
#define ECUM_CONST_BOOLEAN
#define ECUM_CONST_8BIT
#define ECUM_CONST_16BIT
#define ECUM_CONST_32BIT
#define ECUM_CONST_UNSPECIFIED
#define ECUM_APPL_DATA
#define ECUM_APPL_CONST
#define ECUM_APPL_CODE

#define FIM_CODE
#define FIM_VAR_NOINIT
#define FIM_VAR_POWER_ON_INIT
#define FIM_VAR_FAST
#define FIM_VAR
#define FIM_CONST_BOOLEAN
#define FIM_CONST_8BIT
#define FIM_CONST_16BIT
#define FIM_CONST_32BIT
#define FIM_CONST_UNSPECIFIED
#define FIM_APPL_DATA
#define FIM_APPL_CONST
#define FIM_APPL_CODE

#define COMM_CODE
#define COMM_VAR_NOINIT
#define COMM_VAR_POWER_ON_INIT
#define COMM_VAR_FAST
#define COMM_VAR
#define COMM_CONST_BOOLEAN
#define COMM_CONST_8BIT
#define COMM_CONST_16BIT
#define COMM_CONST_32BIT
#define COMM_CONST_UNSPECIFIED
#define COMM_APPL_DATA
#define COMM_APPL_CONST
#define COMM_APPL_CODE

#define WDGM_CODE
#define WDGM_VAR_NOINIT
#define WDGM_VAR_POWER_ON_INIT
#define WDGM_VAR_FAST
#define WDGM_VAR
#define WDGM_CONST_BOOLEAN
#define WDGM_CONST_8BIT
#define WDGM_CONST_16BIT
#define WDGM_CONST_32BIT
#define WDGM_CONST_UNSPECIFIED
#define WDGM_APPL_DATA
#define WDGM_APPL_CONST
#define WDGM_APPL_CODE

#define DET_CODE
#define DET_VAR_NOINIT
#define DET_VAR_POWER_ON_INIT
#define DET_VAR_FAST
#define DET_VAR
#define DET_CONST_BOOLEAN
#define DET_CONST_8BIT
#define DET_CONST_16BIT
#define DET_CONST_32BIT
#define DET_CONST_UNSPECIFIED
#define DET_APPL_DATA
#define DET_APPL_CONST
#define DET_APPL_CODE

#define NVM_CODE
#define NVM_VAR_NOINIT
#define NVM_VAR_POWER_ON_INIT
#define NVM_VAR_FAST
#define NVM_VAR
#define NVM_CONST_BOOLEAN
#define NVM_CONST_8BIT
#define NVM_CONST_16BIT
#define NVM_CONST_32BIT
#define NVM_CONST_UNSPECIFIED
#define NVM_APPL_DATA
#define NVM_APPL_CONST
#define NVM_APPL_CODE

#define FEE_CODE
#define FEE_VAR_NOINIT
#define FEE_VAR_POWER_ON_INIT
#define FEE_VAR_FAST
#define FEE_VAR
#define FEE_CONST_BOOLEAN
#define FEE_CONST_8BIT
#define FEE_CONST_16BIT
#define FEE_CONST_32BIT
#define FEE_CONST_UNSPECIFIED
#define FEE_APPL_DATA
#define FEE_APPL_CONST
#define FEE_APPL_CODE

#define MEMIF_CODE
#define MEMIF_VAR_NOINIT
#define MEMIF_VAR_POWER_ON_INIT
#define MEMIF_VAR_FAST
#define MEMIF_VAR
#define MEMIF_CONST_BOOLEAN
#define MEMIF_CONST_8BIT
#define MEMIF_CONST_16BIT
#define MEMIF_CONST_32BIT
#define MEMIF_CONST_UNSPECIFIED
#define MEMIF_APPL_DATA
#define MEMIF_APPL_CONST
#define MEMIF_APPL_CODE

#define NM_CODE
#define NM_VAR_NOINIT
#define NM_VAR_POWER_ON_INIT
#define NM_VAR_FAST
#define NM_VAR
#define NM_CONST_BOOLEAN
#define NM_CONST_8BIT
#define NM_CONST_16BIT
#define NM_CONST_32BIT
#define NM_CONST_UNSPECIFIED
#define NM_APPL_DATA
#define NM_APPL_CONST
#define NM_APPL_CODE

#define CANNM_CODE
#define CANNM_VAR_NOINIT
#define CANNM_VAR_POWER_ON_INIT
#define CANNM_VAR_FAST
#define CANNM_VAR
#define CANNM_CONST_BOOLEAN
#define CANNM_CONST_8BIT
#define CANNM_CONST_16BIT
#define CANNM_CONST_32BIT
#define CANNM_CONST_UNSPECIFIED
#define CANNM_APPL_DATA
#define CANNM_APPL_CONST
#define CANNM_APPL_CODE

#define FRNM_CODE
#define FRNM_VAR_NOINIT
#define FRNM_VAR_POWER_ON_INIT
#define FRNM_VAR_FAST
#define FRNM_VAR
#define FRNM_CONST_BOOLEAN
#define FRNM_CONST_8BIT
#define FRNM_CONST_16BIT
#define FRNM_CONST_32BIT
#define FRNM_CONST_UNSPECIFIED
#define FRNM_APPL_DATA
#define FRNM_APPL_CONST
#define FRNM_APPL_CODE

#define CANTP_CODE
#define CANTP_VAR_NOINIT
#define CANTP_VAR_POWER_ON_INIT
#define CANTP_VAR_FAST
#define CANTP_VAR
#define CANTP_CONST_BOOLEAN
#define CANTP_CONST_8BIT
#define CANTP_CONST_16BIT
#define CANTP_CONST_32BIT
#define CANTP_CONST_UNSPECIFIED
#define CANTP_APPL_DATA
#define CANTP_APPL_CONST
#define CANTP_APPL_CODE

#define FRTP_CODE
#define FRTP_VAR_NOINIT
#define FRTP_VAR_POWER_ON_INIT
#define FRTP_VAR_FAST
#define FRTP_VAR
#define FRTP_CONST_BOOLEAN
#define FRTP_CONST_8BIT
#define FRTP_CONST_16BIT
#define FRTP_CONST_32BIT
#define FRTP_CONST_UNSPECIFIED
#define FRTP_APPL_DATA
#define FRTP_APPL_CONST
#define FRTP_APPL_CODE

#define EA_CODE
#define EA_VAR_NOINIT
#define EA_VAR_POWER_ON_INIT
#define EA_VAR_FAST
#define EA_VAR
#define EA_CONST_BOOLEAN
#define EA_CONST_8BIT
#define EA_CONST_16BIT
#define EA_CONST_32BIT
#define EA_CONST_UNSPECIFIED
#define EA_APPL_DATA
#define EA_APPL_CONST
#define EA_APPL_CODE

#define WDGIF_CODE
#define WDGIF_VAR_NOINIT
#define WDGIF_VAR_POWER_ON_INIT
#define WDGIF_VAR_FAST
#define WDGIF_VAR
#define WDGIF_CONST_BOOLEAN
#define WDGIF_CONST_8BIT
#define WDGIF_CONST_16BIT
#define WDGIF_CONST_32BIT
#define WDGIF_CONST_UNSPECIFIED
#define WDGIF_APPL_DATA
#define WDGIF_APPL_CONST
#define WDGIF_APPL_CODE

#define COM_CODE
#define COM_VAR_NOINIT
#define COM_VAR_POWER_ON_INIT
#define COM_VAR_FAST
#define COM_VAR
#define COM_CONST_BOOLEAN
#define COM_CONST_8BIT
#define COM_CONST_16BIT
#define COM_CONST_32BIT
#define COM_CONST_UNSPECIFIED
#define COM_APPL_DATA
#define COM_APPL_CONST
#define COM_APPL_CODE

#define PDUR_CODE
#define PDUR_VAR_NOINIT
#define PDUR_VAR_POWER_ON_INIT
#define PDUR_VAR_FAST
#define PDUR_VAR
#define PDUR_CONST_BOOLEAN
#define PDUR_CONST_8BIT
#define PDUR_CONST_16BIT
#define PDUR_CONST_32BIT
#define PDUR_CONST_UNSPECIFIED
#define PDUR_APPL_DATA
#define PDUR_APPL_CONST
#define PDUR_APPL_CODE

#define IPDUM_CODE
#define IPDUM_VAR_NOINIT
#define IPDUM_VAR_POWER_ON_INIT
#define IPDUM_VAR_FAST
#define IPDUM_VAR
#define IPDUM_CONST_BOOLEAN
#define IPDUM_CONST_8BIT
#define IPDUM_CONST_16BIT
#define IPDUM_CONST_32BIT
#define IPDUM_CONST_UNSPECIFIED
#define IPDUM_APPL_DATA
#define IPDUM_APPL_CONST
#define IPDUM_APPL_CODE

#define DCM_CODE
#define DCM_VAR_NOINIT
#define DCM_VAR_POWER_ON_INIT
#define DCM_VAR_FAST
#define DCM_VAR
#define DCM_CONST_BOOLEAN
#define DCM_CONST_8BIT
#define DCM_CONST_16BIT
#define DCM_CONST_32BIT
#define DCM_CONST_UNSPECIFIED
#define DCM_APPL_DATA
#define DCM_APPL_CONST
#define DCM_APPL_CODE

#define DEM_CODE
#define DEM_VAR_NOINIT
#define DEM_VAR_POWER_ON_INIT
#define DEM_VAR_FAST
#define DEM_VAR
#define DEM_CONST_BOOLEAN
#define DEM_CONST_8BIT
#define DEM_CONST_16BIT
#define DEM_CONST_32BIT
#define DEM_CONST_UNSPECIFIED
#define DEM_APPL_DATA
#define DEM_APPL_CONST
#define DEM_APPL_CODE

#define CANIF_CODE
#define CANIF_VAR_NOINIT
#define CANIF_VAR_POWER_ON_INIT
#define CANIF_VAR_FAST
#define CANIF_VAR
#define CANIF_CONST_BOOLEAN
#define CANIF_CONST_8BIT
#define CANIF_CONST_16BIT
#define CANIF_CONST_32BIT
#define CANIF_CONST_UNSPECIFIED
#define CANIF_APPL_DATA
#define CANIF_APPL_CONST
#define CANIF_APPL_CODE

#define FRIF_CODE
#define FRIF_VAR_NOINIT
#define FRIF_VAR_POWER_ON_INIT
#define FRIF_VAR_FAST
#define FRIF_VAR
#define FRIF_CONST_BOOLEAN
#define FRIF_CONST_8BIT
#define FRIF_CONST_16BIT
#define FRIF_CONST_32BIT
#define FRIF_CONST_UNSPECIFIED
#define FRIF_APPL_DATA
#define FRIF_APPL_CONST
#define FRIF_APPL_CODE

#define LINIF_CODE
#define LINIF_VAR_NOINIT
#define LINIF_VAR_POWER_ON_INIT
#define LINIF_VAR_FAST
#define LINIF_VAR
#define LINIF_CONST_BOOLEAN
#define LINIF_CONST_8BIT
#define LINIF_CONST_16BIT
#define LINIF_CONST_32BIT
#define LINIF_CONST_UNSPECIFIED
#define LINIF_APPL_DATA
#define LINIF_APPL_CONST
#define LINIF_APPL_CODE

#define LINNM_CODE
#define LINNM_VAR_NOINIT
#define LINNM_VAR_POWER_ON_INIT
#define LINNM_VAR_FAST
#define LINNM_VAR
#define LINNM_CONST_BOOLEAN
#define LINNM_CONST_8BIT
#define LINNM_CONST_16BIT
#define LINNM_CONST_32BIT
#define LINNM_CONST_UNSPECIFIED
#define LINNM_APPL_DATA
#define LINNM_APPL_CONST
#define LINNM_APPL_CODE

#define CANTRCV_CODE
#define CANTRCV_VAR_NOINIT
#define CANTRCV_VAR_POWER_ON_INIT
#define CANTRCV_VAR_FAST
#define CANTRCV_VAR
#define CANTRCV_CONST_BOOLEAN
#define CANTRCV_CONST_8BIT
#define CANTRCV_CONST_16BIT
#define CANTRCV_CONST_32BIT
#define CANTRCV_CONST_UNSPECIFIED
#define CANTRCV_APPL_DATA
#define CANTRCV_APPL_CONST
#define CANTRCV_APPL_CODE

#define FRTRCV_CODE
#define FRTRCV_VAR_NOINIT
#define FRTRCV_VAR_POWER_ON_INIT
#define FRTRCV_VAR_FAST
#define FRTRCV_VAR
#define FRTRCV_CONST_BOOLEAN
#define FRTRCV_CONST_8BIT
#define FRTRCV_CONST_16BIT
#define FRTRCV_CONST_32BIT
#define FRTRCV_CONST_UNSPECIFIED
#define FRTRCV_APPL_DATA
#define FRTRCV_APPL_CONST
#define FRTRCV_APPL_CODE

#define CAN_CODE
#define CAN_VAR_NOINIT
#define CAN_VAR_POWER_ON_INIT
#define CAN_VAR_FAST
#define CAN_VAR
#define CAN_CONST_BOOLEAN
#define CAN_CONST_8BIT
#define CAN_CONST_16BIT
#define CAN_CONST_32BIT
#define CAN_CONST_UNSPECIFIED
#define CAN_APPL_DATA
#define CAN_APPL_CONST
#define CAN_APPL_CODE

#define FR_CODE
#define FR_VAR_NOINIT
#define FR_VAR_POWER_ON_INIT
#define FR_VAR_FAST
#define FR_VAR
#define FR_CONST_BOOLEAN
#define FR_CONST_8BIT
#define FR_CONST_16BIT
#define FR_CONST_32BIT
#define FR_CONST_UNSPECIFIED
#define FR_APPL_DATA
#define FR_APPL_CONST
#define FR_APPL_CODE

#define LIN_CODE
#define LIN_VAR_NOINIT
#define LIN_VAR_POWER_ON_INIT
#define LIN_VAR_FAST
#define LIN_VAR
#define LIN_CONST_BOOLEAN
#define LIN_CONST_8BIT
#define LIN_CONST_16BIT
#define LIN_CONST_32BIT
#define LIN_CONST_UNSPECIFIED
#define LIN_APPL_DATA
#define LIN_APPL_CONST
#define LIN_APPL_CODE

#define SPI_CODE
#define SPI_VAR_NOINIT
#define SPI_VAR_POWER_ON_INIT
#define SPI_VAR_FAST
#define SPI_VAR
#define SPI_CONST_BOOLEAN
#define SPI_CONST_8BIT
#define SPI_CONST_16BIT
#define SPI_CONST_32BIT
#define SPI_CONST_UNSPECIFIED
#define SPI_APPL_DATA
#define SPI_APPL_CONST
#define SPI_APPL_CODE

#define EEP_CODE
#define EEP_VAR_NOINIT
#define EEP_VAR_POWER_ON_INIT
#define EEP_VAR_FAST
#define EEP_VAR
#define EEP_CONST_BOOLEAN
#define EEP_CONST_8BIT
#define EEP_CONST_16BIT
#define EEP_CONST_32BIT
#define EEP_CONST_UNSPECIFIED
#define EEP_APPL_DATA
#define EEP_APPL_CONST
#define EEP_APPL_CODE

#define FLS_CODE
#define FLS_VAR_NOINIT
#define FLS_VAR_POWER_ON_INIT
#define FLS_VAR_FAST
#define FLS_VAR
#define FLS_CONST_BOOLEAN
#define FLS_CONST_8BIT
#define FLS_CONST_16BIT
#define FLS_CONST_32BIT
#define FLS_CONST_UNSPECIFIED
#define FLS_APPL_DATA
#define FLS_APPL_CONST
#define FLS_APPL_CODE

#define RAMTST_CODE
#define RAMTST_VAR_NOINIT
#define RAMTST_VAR_POWER_ON_INIT
#define RAMTST_VAR_FAST
#define RAMTST_VAR
#define RAMTST_CONST_BOOLEAN
#define RAMTST_CONST_8BIT
#define RAMTST_CONST_16BIT
#define RAMTST_CONST_32BIT
#define RAMTST_CONST_UNSPECIFIED
#define RAMTST_APPL_DATA
#define RAMTST_APPL_CONST
#define RAMTST_APPL_CODE

#define GPT_CODE
#define GPT_VAR_NOINIT
#define GPT_VAR_POWER_ON_INIT
#define GPT_VAR_FAST
#define GPT_VAR
#define GPT_CONST_BOOLEAN
#define GPT_CONST_8BIT
#define GPT_CONST_16BIT
#define GPT_CONST_32BIT
#define GPT_CONST_UNSPECIFIED
#define GPT_APPL_DATA
#define GPT_APPL_CONST
#define GPT_APPL_CODE

#define MCU_CODE
#define MCU_VAR_NOINIT
#define MCU_VAR_POWER_ON_INIT
#define MCU_VAR_FAST
#define MCU_VAR
#define MCU_CONST_BOOLEAN
#define MCU_CONST_8BIT
#define MCU_CONST_16BIT
#define MCU_CONST_32BIT
#define MCU_CONST_UNSPECIFIED
#define MCU_APPL_DATA
#define MCU_APPL_CONST
#define MCU_APPL_CODE

#define WDG_CODE
#define WDG_VAR_NOINIT
#define WDG_VAR_POWER_ON_INIT
#define WDG_VAR_FAST
#define WDG_VAR
#define WDG_CONST_BOOLEAN
#define WDG_CONST_8BIT
#define WDG_CONST_16BIT
#define WDG_CONST_32BIT
#define WDG_CONST_UNSPECIFIED
#define WDG_APPL_DATA
#define WDG_APPL_CONST
#define WDG_APPL_CODE

#define DIO_CODE
#define DIO_VAR_NOINIT
#define DIO_VAR_POWER_ON_INIT
#define DIO_VAR_FAST
#define DIO_VAR
#define DIO_CONST_BOOLEAN
#define DIO_CONST_8BIT
#define DIO_CONST_16BIT
#define DIO_CONST_32BIT
#define DIO_CONST_UNSPECIFIED
#define DIO_APPL_DATA
#define DIO_APPL_CONST
#define DIO_APPL_CODE

#define PWM_CODE
#define PWM_VAR_NOINIT
#define PWM_VAR_POWER_ON_INIT
#define PWM_VAR_FAST
#define PWM_VAR
#define PWM_CONST_BOOLEAN
#define PWM_CONST_8BIT
#define PWM_CONST_16BIT
#define PWM_CONST_32BIT
#define PWM_CONST_UNSPECIFIED
#define PWM_APPL_DATA
#define PWM_APPL_CONST
#define PWM_APPL_CODE

#define ICU_CODE
#define ICU_VAR_NOINIT
#define ICU_VAR_POWER_ON_INIT
#define ICU_VAR_FAST
#define ICU_VAR
#define ICU_CONST_BOOLEAN
#define ICU_CONST_8BIT
#define ICU_CONST_16BIT
#define ICU_CONST_32BIT
#define ICU_CONST_UNSPECIFIED
#define ICU_APPL_DATA
#define ICU_APPL_CONST
#define ICU_APPL_CODE

#define ADC_CODE
#define ADC_VAR_NOINIT
#define ADC_VAR_POWER_ON_INIT
#define ADC_VAR_FAST
#define ADC_VAR
#define ADC_CONST_BOOLEAN
#define ADC_CONST_8BIT
#define ADC_CONST_16BIT
#define ADC_CONST_32BIT
#define ADC_CONST_UNSPECIFIED
#define ADC_APPL_DATA
#define ADC_APPL_CONST
#define ADC_APPL_CODE

#define PORT_CODE
#define PORT_VAR_NOINIT
#define PORT_VAR_POWER_ON_INIT
#define PORT_VAR_FAST
#define PORT_VAR
#define PORT_CONST_BOOLEAN
#define PORT_CONST_8BIT
#define PORT_CONST_16BIT
#define PORT_CONST_32BIT
#define PORT_CONST_UNSPECIFIED
#define PORT_APPL_DATA
#define PORT_APPL_CONST
#define PORT_APPL_CODE

#define SCHM_CODE
#define SCHM_VAR_NOINIT
#define SCHM_VAR_POWER_ON_INIT
#define SCHM_VAR_FAST
#define SCHM_VAR
#define SCHM_CONST_BOOLEAN
#define SCHM_CONST_8BIT
#define SCHM_CONST_16BIT
#define SCHM_CONST_32BIT
#define SCHM_CONST_UNSPECIFIED
#define SCHM_APPL_DATA
#define SCHM_APPL_CONST
#define SCHM_APPL_CODE

#define CANSM_CODE
#define CANSM_VAR_NOINIT
#define CANSM_VAR_POWER_ON_INIT
#define CANSM_VAR_FAST
#define CANSM_VAR
#define CANSM_CONST_BOOLEAN
#define CANSM_CONST_8BIT
#define CANSM_CONST_16BIT
#define CANSM_CONST_32BIT
#define CANSM_CONST_UNSPECIFIED
#define CANSM_APPL_DATA
#define CANSM_APPL_CONST
#define CANSM_APPL_CODE

#define LINSM_CODE
#define LINSM_VAR_NOINIT
#define LINSM_VAR_POWER_ON_INIT
#define LINSM_VAR_FAST
#define LINSM_VAR
#define LINSM_CONST_BOOLEAN
#define LINSM_CONST_8BIT
#define LINSM_CONST_16BIT
#define LINSM_CONST_32BIT
#define LINSM_CONST_UNSPECIFIED
#define LINSM_APPL_DATA
#define LINSM_APPL_CONST
#define LINSM_APPL_CODE

#define FRSM_CODE
#define FRSM_VAR_NOINIT
#define FRSM_VAR_POWER_ON_INIT
#define FRSM_VAR_FAST
#define FRSM_VAR
#define FRSM_CONST_BOOLEAN
#define FRSM_CONST_8BIT
#define FRSM_CONST_16BIT
#define FRSM_CONST_32BIT
#define FRSM_CONST_UNSPECIFIED
#define FRSM_APPL_DATA
#define FRSM_APPL_CONST
#define FRSM_APPL_CODE

#define CRC_CODE
#define CRC_VAR_NOINIT
#define CRC_VAR_POWER_ON_INIT
#define CRC_VAR_FAST
#define CRC_VAR
#define CRC_CONST_BOOLEAN
#define CRC_CONST_8BIT
#define CRC_CONST_16BIT
#define CRC_CONST_32BIT
#define CRC_CONST_UNSPECIFIED
#define CRC_APPL_DATA
#define CRC_APPL_CONST
#define CRC_APPL_CODE

#endif	/* __COMPILER_CFG_H */

